# Generated by Django 4.2 on 2023-04-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Celular')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, default=None, max_length=600, null=True, verbose_name='Descripción')),
                ('unit_price', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Valor unitario')),
                ('expiration_date', models.DateField(blank=True, default=None, null=True, verbose_name='Fecha de caducidad')),
            ],
        ),
    ]
