# Generated by Django 4.2 on 2023-04-12 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de caducidad'),
        ),
    ]
