# Generated by Django 4.2 on 2023-05-01 23:51

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_alter_product_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Colores'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Descuento'),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, default=None, max_length=600, null=True, verbose_name='Características'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='product_images', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='product',
            name='out_of_stock',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Agotado'),
        ),
        migrations.AddField(
            model_name='product',
            name='previous_price',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Precio anterior'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Precio'),
        ),
        migrations.AddField(
            model_name='product',
            name='star_rate',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Unidades disponibles'),
        ),
        migrations.AddField(
            model_name='product',
            name='value',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 5, 1), null=True, verbose_name='Fecha de caducidad'),
        ),
    ]
