# Generated by Django 4.2 on 2023-05-02 00:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_alter_product_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='value',
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.CharField(blank=True, default='Black', max_length=50, null=True, verbose_name='Colores'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='\n        The colorful leaves rustled beneath my feet as I walked through the tranquil \n        forest. The gentle breeze carried the scent of pine and fresh air, and the \n        sound of a nearby stream provided a soothing soundtrack. As I gazed up at the \n        clear blue sky, I felt grateful for this moment of peace and serenity.', max_length=600, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=20, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, default='7 velocidades', max_length=600, null=True, verbose_name='Características'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='previous_price',
            field=models.PositiveIntegerField(blank=True, default=149900, null=True, verbose_name='Precio anterior'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=129900, null=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='star_rate',
            field=models.DecimalField(blank=True, decimal_places=1, default=4.2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(blank=True, default=30, null=True, verbose_name='Unidades disponibles'),
        ),
    ]
