# Generated by Django 4.2 on 2023-05-06 00:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_remove_product_value_alter_product_colors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 5, 4, 6, 0), verbose_name='Fecha y hora en que se agregó'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
