# Generated by Django 4.2 on 2023-05-06 00:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0007_product_added_at_product_is_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='added_at',
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha y hora en que se agregó'),
            preserve_default=False,
        ),
    ]
